version: "3"

services:

  virtuoso-goa-human:
    image: openlink/virtuoso-opensource-7:latest
    restart: unless-stopped
    volumes:
      - ./data:/opt/virtuoso-opensource/database/data
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=${PASSWORD:-dba}
      # - SPARQL_UPDATE=true
      ## Choose between dynamic URI or define it yourself
      - VIRT_URIQA_DynamicLocal=1
      # - VIRT_URIQA_DefaultHost=your.url.org
      # - DEFAULT_GRAPH=https://w3id.org/um/
      ## Uncomment the following lines for large amount of data
      # - VIRT_Database_ErrorLogLevel=2 # default: 7 is maximum logs
      # - VIRT_HTTPServer_HTTPThreadSize=280000
      # - VIRT_URIQA_DynamicLocal=1
      # - VIRT_SPARQL_ResultSetMaxRows=1048576
      # - VIRT_SPARQL_MaxQueryCostEstimationTime=200000
      # - VIRT_SPARQL_MaxQueryExecutionTime=1000000
      # - VIRT_Database_MaxCheckpointRemap=125000
      # - VIRT_TempDatabase_MaxCheckpointRemap=125000
      # - VIRT_Parameters_TempDBSize=100000000
      # - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      # - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_SPARQL_ShortenLongURIs=1
      # - VIRT_SPARQL_MaxCacheExpiration=1
      # - VIRT_SPARQL_ExternalQuerySource=1
      # - VIRT_SPARQL_ExternalXsltSource=1
      # - VIRT_Parameters_DirsAllowed=".,/usr/local/virtuoso-opensource/share/virtuoso/vad,/data"

      # # Deploy using https://github.com/nginx-proxy
      # - VIRTUAL_PORT=8890
      # - VIRTUAL_HOST=your.url.org
      # - LETSENCRYPT_HOST=your.url.org
